export const allkeys = {
  // Auth
  USER_LOGIN: "USER_LOGIN",
  USER_SIGNUP: "USER_SIGNUP",
  EMAIL_VERIFY: "EMAIL_VERIFY",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  OTP_VERIFY: "OTP_VERIFY",
  RESET_PASSWORD: "RESET_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  PROFILE_DETAILS: "PROFILE_DETAILS",
  PROFILE_UPDATE: "PROFILE_UPDATE",

  // Projects
  PROJECT_LIST: "PROJECT_LIST",
  PROJECT_DETAILS: "PROJECT_DETAILS",
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_UPDATE: "PROJECT_UPDATE",
  PROJECT_DELETE: "PROJECT_DELETE",
  ALL_PROJECT_LIST: "ALL_PROJECT_LIST",

  // Categories
  CATEGORY_LIST: "CATEGORY_LIST",

  // Feedbacks
  FEEDBACK_CREATE: "FEEDBACK_CREATE",
  FEEDBACK_LIST: "FEEDBACK_LIST",
  FEEDBACK_UPDATE: "FEEDBACK_UPDATE",
  FEEDBACK_DELETE: "FEEDBACK_DELETE",
  FEEDBACK_REPLY: "FEEDBACK_REPLY",
  FEEDBACK_MARK_AS_SAVE: "FEEDBACK_MARK_AS_SAVE",
  ALL_SAVED_FEEDBACKS: "ALL_SAVED_FEEDBACKS",

  //Dashboard
  DASHBOARD_COUNT: "DASHBOARD_COUNT",
  DASHBOARD_GRAPH: "DASHBOARD_GRAPH",
  DASHBOARD_FEEDBACKS: "DASHBOARD_FEEDBACKS",
} as const;
